=== nwself/bus-server/BusImpl/schema/bus.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schema.theboardgame.party/bus.schema.json",
  "title": "Bus: The Game",
  "description": "A state of the game Bus",
  "type": "object",
  "properties": {
    "slug": {
      "description": "Unique identifier to this game",
      "type": "string"
    },
    "phase": {
      "description": "Current game phase",
      "type": "string",
      "enum": [
        "place-workers",
        "build-road",
        "new-bus",
        "more-people",
        "new-buildings",
        "stop-time",
        "vroom",
        "first-player"
      ]
    },
    "activePlayer": {
      "description": "Current player (can this be limited to the keys of the players object?",
      "type": "string"
    },
    "players": {
      "description": "All players in this game",
      "type": "object",
      "patternProperties": {
        ".*": {
          "$ref": "https://schema.theboardgame.party/player.bus.schema.json"
        }
      },
      "minItems": 2,
      "uniqueItems": true
    },
    "workerAreas": {
      "description": "Worker areas on the board",
      "type": "object",
      "patternProperties": {
        ".*": {
          "$ref": "https://schema.theboardgame.party/workerarea.bus.schema.json"
        }
      },
      "minItems": 7,
      "maxItems": 7,
      "uniqueItems": true
    },
    "timeyWimeys": {
      "description": "Number of clock stoppages remaining",
      "type": "number",
      "minimum": 0,
      "maximum": 5
    },
    "time": {
      "description": "Number of clock stoppages remaining",
      "type": "string",
      "enum": [
        "home",
        "work",
        "pub"
      ]
    },
    "buildings": {
      "description": "Currently placed buildings",
      "type": "object",
      "patternProperties": {
        "\\d": {
          "description": "Type of building placed at node with ID == key",
          "type": "string",
          "enum": [
            "home",
            "work",
            "pub"
          ]
        }
      },
      "additionalProperties": false
    },
    "people": {
      "description": "Locations of passengers on board",
      "type": "object",
      "patternProperties": {
        "\\d": {
          "description": "Number of passengers at node with ID == key",
          "type": "number"
        }
      },
      "additionalProperties": false
    },
    "maxBuses": {
      "description": "Max of each players bus count",
      "type": "number",
      "minimum": 1
    },
    "information": {
      "description": "Information front end should display",
      "type": "array"
    },
    "remainingPeople": {
      "description": "Number of passengers left to be added to board",
      "type": "number",
      "minimum": 0,
      "maximum": 16
    }
  }
}

=== nwself/bus-server/BusImpl/schema/sample_state.json
{
    "slug": "abc",
    "phase": "stop-time",
    "activePlayer": "piestastedgood",
    "players":
    {
        "tripswithtires":
        {
            "name": "tripswithtires",
            "color": "yellow",
            "workers": 13,
            "canPass": false,
            "workersUsedThisPhase": 0,
            "passed": true,
            "roads":
            [
                42,
                60,
                1,
                45,
                47,
                48,
                57,
                62
            ],
            "canRoad":
            [
                58,
                68
            ],
            "startNode": 30,
            "endNode": 30,
            "busCount": 3,
            "timeyWimeys": 0,
            "hasFirstPlayerToken": true
        },
        "piestastedgood":
        {
            "name": "piestastedgood",
            "color": "red",
            "workers": 13,
            "canPass": false,
            "workersUsedThisPhase": 0,
            "passed": true,
            "roads":
            [
                4
            ],
            "canRoad":
            [
                2,
                3,
                23,
                5,
                14,
                25,
                30
            ],
            "startNode": 1,
            "endNode": 4,
            "busCount": 3,
            "timeyWimeys": 0,
            "hasFirstPlayerToken": false
        }
    },
    "workerAreas":
    {
        "build-road":
        {
            "name": "build-road",
            "size": 6,
            "reverse": true,
            "workers":
            [],
            "actions":
            []
        },
        "new-bus":
        {
            "name": "new-bus",
            "size": 1,
            "reverse": false,
            "workers":
            [],
            "actions":
            []
        },
        "more-people":
        {
            "name": "more-people",
            "size": 6,
            "reverse": false,
            "workers":
            [],
            "actions":
            []
        },
        "new-buildings":
        {
            "name": "new-buildings",
            "size": 6,
            "reverse": true,
            "workers":
            [],
            "actions":
            []
        },
        "stop-time":
        {
            "name": "stop-time",
            "size": 1,
            "reverse": false,
            "workers":
            [
                "piestastedgood"
            ],
            "actions":
            [
                [
                    "piestastedgood",
                    1
                ]
            ]
        },
        "vroom":
        {
            "name": "vroom",
            "size": 6,
            "reverse": false,
            "workers":
            [],
            "actions":
            []
        },
        "first-player":
        {
            "name": "first-player",
            "size": 1,
            "reverse": false,
            "workers":
            [],
            "actions":
            []
        }
    },
    "timeyWimeys": 5,
    "time": "work",
    "buildings":
    {
        "2": "work",
        "3": "work",
        "8": "home"
    },
    "people":
    {
        "31": 4,
        "9": 3
    },
    "maxBuses": 3,
    "information":
    [
        {
            "who": "piestastedgood",
            "what": "new-bus"
        }
    ],
    "remainingPeople": 6
}
